apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: santedb
  name: santedb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: santedb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: santedb
    spec:
      containers:
      - env:
        - name: SDB_DB_AUDIT
          value: server=sdb-postgres;port=5432; database=auditdb; user id=santedb;
            password=SanteDB123; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
        - name: SDB_DB_AUDIT_PROVIDER
          value: Npgsql
        - name: SDB_DB_MAIN
          value: server=sdb-postgres;port=5432; database=santedb; user id=santedb;
            password=SanteDB123; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
        - name: SDB_DB_MAIN_PROVIDER
          value: Npgsql
        - name: SDB_DELAY_START
          value: "5000"
        - name: SDB_FEATURE
          value: LOG;DATA_POLICY;AUDIT_REPO;ADO;PUBSUB_ADO;RAMCACHE;SEC;SWAGGER;OPENID;FHIR;HL7;HDSI;AMI;BIS;MDM;MATCHING
        - name: SDB_LOG_LEVEL
          value: Verbose
        - name: SDB_MATCHING_MODE
          value: WEIGHTED
        - name: SDB_MDM_AUTO_MERGE
          value: "false"
        - name: SDB_MDM_RESOURCE
          value: Patient=org.santedb.matching.patient.default
        - name: SDB_REDIS_SERVER
          value: sdb-redis:6379
        image: santesuite/santedb-mpi:2.1.3
        imagePullPolicy: ""
        name: santedb-mpi
        ports:
        - containerPort: 8080
        - containerPort: 2100
        resources: {}
        volumeMounts:
        - mountPath: /santedb
          name: santedb-mpi-dev
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: santedb-mpi-dev
        persistentVolumeClaim:
          claimName: santedb-mpi-dev
status: {}
